require:
  - rubocop-rails

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Style/FrozenStringLiteralComment:
 Enabled: false

Documentation:
 Enabled: false

Style/StringLiterals:
 Enabled: false
